Completed React accordion component - Daniel Rosenbaum.
danielwrosenbaum/c0121-code-solutions pull request #123
Opened 2021-03-27 21:49 UTC by danielwrosenbaum

![Accordion](https://user-images.githubusercontent.com/74999873/112735840-927cd980-8f0b-11eb-86f1-a5ff9bc854b9.gif)

2021-03-28 23:40 UTC, thebearingedge requested changes
Great, just a little bit of clean up needed.

2021-03-28 23:40 UTC, thebearingedge commented on react-accordion-component/src/accordion.jsx
> +      isClicked: false,
This `isClicked` isn't really used for anything.

2021-03-28 23:40 UTC, thebearingedge commented on react-accordion-component/src/accordion.jsx
> +];
This array should be passed as a prop in your `index.jsx`.

2021-03-28 23:40 UTC, thebearingedge commented on react-accordion-component/src/accordion.jsx
> +        target: event.target
Try `null` instead of `event.target`. In general, we do not store DOM elements in state.

2021-03-29 00:44 UTC, thebearingedge requested changes
That `isClicked` can go.

2021-03-29 00:45 UTC, danielwrosenbaum commented
> That `isClicked` can go.

right sorry! changed that but then had to go back to fix something else and forgot to switch that back. will fix now!

2021-03-29 00:47 UTC, thebearingedge approved these changes

2021-03-29 00:48 UTC, merged