Completed Javascript Carousel Exercise - Daniel Rosenbaum
danielwrosenbaum/c0121-code-solutions pull request #64
Opened 2021-02-18 03:25 UTC by danielwrosenbaum

![Screen Shot 2021-02-17 at 7 25 01 PM](https://user-images.githubusercontent.com/74999873/108300811-da168580-7155-11eb-86c1-b485386f232f.png)

2021-02-19 19:24 UTC, codingcodymiller requested changes
Great work so far!! Please see my notes

2021-02-19 19:24 UTC, codingcodymiller commented on javascript-carousel/main.js
> +      if (i === $viewList.length) {
This could be an `else if`

2021-02-19 19:24 UTC, codingcodymiller commented on javascript-carousel/main.js
> +var timer = setInterval(changeImage, 3000);
You should do this at the top of the page with your other global variables

2021-02-19 19:24 UTC, codingcodymiller commented on javascript-carousel/main.js
> +$rightArrow.addEventListener('click', changeImageWithRightArrow);
Same, do this at the top of the page

2021-02-19 19:24 UTC, codingcodymiller commented on javascript-carousel/main.js
> +$leftArrow.addEventListener('click', changeImageWithLeftArrow);
Same, do this at the top of the page

2021-02-19 19:24 UTC, codingcodymiller commented on javascript-carousel/main.js
> +$navBar.addEventListener('click', changeButton);
Same, do this at the top of the page

2021-02-21 21:28 UTC, thebearingedge requested changes
Try to think of your code as doing 3 tasks
- listen for clicks
- determine the appropriate index to activate (left or right)
- active the index

If you define functions that do those things, your code will have much less repetition in it.

2021-02-21 21:28 UTC, thebearingedge commented on javascript-carousel/main.js
> +      }
This code is repeated quite a bit. See if you can define a function that takes a new index and updates the DOM accordingly. Then, re-use that function.

```js
function activateIndex(index) {

}
```

2021-03-08 04:32 UTC, thebearingedge approved these changes

2021-03-08 05:39 UTC, merged